### PR TITLE
Improve how env vars are brought in, setup PostgreSQL in dev and prod

### PR DESCRIPTION
**Pull request by cywang117**
This theoretically would work, but I may need to test it in a personal heroku repo first. In the meantime, opening a PR for code review.

Change-type: patch
Signed-off-by: Christina Wang <christina@balena.io>

### CODE REVIEW

**Review by stathismor — APPROVED** [review]
- FMI, why are the env files written programmatically?
- I guess the script files could be in TS that we either run with `ts-node` or build in some directory.

**Comment by cywang117** [comment]
@stathismor 
> why are the env files written programmatically?

This became necessary for me because I was developing with Postgres locally.. I needed to add my credentials without risking them getting committed because I forgot. `scripts/dev.ts` and `scripts/postinstall.ts` (I changed them to TS per your suggestion in bullet 2!) both came from having to develop with Postgres locally actually. Now we can specify `DB=pg|sqlite3 npm run dev` to develop with one or the other. The default is `sqlite3` (see `dev.ts` for more details)

cc @mehalter @jmakivic Ready for review!

Anyways, I've rebased and made some changes, you should be able to see the Postgres integration working in my personal test deployment: https://cluebot-server-test.herokuapp.com/

You may perform the following manual tests to see that the production database functionality is healthy:
- List all players (i.e. people that have answered at least once with `GET /api/players`
- List all answers for current question (from Google Sheets) with `GET /api/answers`
- Answer the question as a new player with `POST /api/answer` and a body of `{ handle, answer }`, then see changes propagated at `GET /api/players` & `GET /api/answers`
- Update an answer for the current player with `POST /api/answer` and a body of `{ handle, answer }`  then view changes at `/api/answers`

I've skipped a lot of the tests in the tests/ directory since they only work with the old, pre-Google Sheets implementation method. A future improvement could be to write better tests with a test-env-only Google Sheets.

I already deployed this to mighty-refuge-11253 as well, since the old deployment wasn't working anyway.. I haven't tested cluebot integration however. I would expect that `cluebot leave|join` breaks but everything else works. If someone could test cluebot integration in Flowdock that would be much appreciated.

If cluebot integration goes well, then these cluebot-server changes should be enough for making sure the basic game loop works (without adding new features like votes, answer history, etc.)

**Comment by mehalter** [comment]
@cywang117 should we go ahead and remove the `leave|join` functionality since we aren't going to be using it anyway?

**Comment by cywang117** [comment]
>  remove the `leave|join` functionality 

@mehalter Agreed!

**Pull request merged**
